### ISSUE TITLE
Comentarios de la revisión

### ISSUE THREAD

**Issue by mikeguzman** [una-eif506-18G02/lab-1-html-css-bryjohseb#1]
1. Por qué esta usando un "`<div class="article">` ó `<div class="section" >`" si puede usar todos los elementos estructurales de HTML5?
2. En el aside usted dibujo un cuadro con una X, cuando en realidad es la imagen del estudiante. Recuerda que un Wireframe es como se ven los elementos estructurales en el sitio, NUNCA tienen que quedar visualmente igual al wireframe, cuando tiene que ser visualmente similar es si yo les paso un Mockup (revisa la documentación que esta en los PDF con respecto a este tema.
3. En la página Groups, es lo mismo tiene que meter una imagen dentro del párrafo y alinearla con el float.

**Comment by bryjohseb** [comment]
Los cambios han sido realizados, con exito..!!
